<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props"></Import>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AssemblyName>CadentManagement.Migrator</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>CadentManagement.Migrator</PackageId>
    <UserSecretsId>MyCompanyName-CadentManagement-894FDFC1-6482-4A56-926A-3C46C9FE0329</UserSecretsId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <LangVersion>latest</LangVersion>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>
  <ItemGroup>
    <None Update="appsettings.json;log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Abp.Castle.Log4Net" Version="11.3.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CadentManagement.EntityFrameworkCore\CadentManagement.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>